import 'dart:math';

import 'package:hive/hive.dart';

import '../models/exercise.dart';
import '../models/cardio_entry.dart';
import '../models/cardio_template.dart';
import '../models/program_block.dart';
import '../models/readiness_entry.dart';
import '../models/scheduled_workout.dart';
import '../models/set_entry.dart';
import '../models/workout.dart';
import '../models/workout_template.dart';
import 'workout_reminder_service.dart';

class ProgramService {
  ProgramService._();

  static Box<ProgramBlock> _programBox() => Hive.box<ProgramBlock>('program_blocks');
  static Box<ScheduledWorkout> _scheduleBox() => Hive.box<ScheduledWorkout>('scheduled_workouts');
  static Box<WorkoutTemplate> _strengthTemplates() => Hive.box<WorkoutTemplate>('templates');
  static Box<CardioTemplate> _cardioTemplates() => Hive.box<CardioTemplate>('cardio_templates');

  static ProgramBlock? programForSchedule(ScheduledWorkout schedule) {
    final key = schedule.programKey;
    if (key == null) return null;
    return _programBox().get(key);
  }

  static Future<int> upsertProgram(ProgramBlock block, {int? key}) async {
    if (key == null) return _programBox().add(block);
    await _programBox().put(key, block);
    return key;
  }

  static Future<void> regenerateSchedulesForProgram({
    required int programKey,
    bool removeExistingAutoGenerated = true,
  }) async {
    final program = _programBox().get(programKey);
    if (program == null || !program.isActive || program.sessions.isEmpty) return;

    if (removeExistingAutoGenerated) {
      final toRemove = <int>[];
      for (final schedule in _scheduleBox().values) {
        if (schedule.programKey != programKey) continue;
        if (!schedule.isAutoGenerated) continue;
        if (schedule.isCompleted || schedule.linkedWorkoutKey != null) continue;
        toRemove.add(schedule.key as int);
      }
      for (final key in toRemove) {
        await WorkoutReminderService.instance.cancelReminder(key);
        await _scheduleBox().delete(key);
      }
    }

    final sortedSessions = [...program.sessions]
      ..sort((a, b) {
        final byDay = a.weekDay.compareTo(b.weekDay);
        if (byDay != 0) return byDay;
        final byHour = a.hour.compareTo(b.hour);
        if (byHour != 0) return byHour;
        return a.minute.compareTo(b.minute);
      });

    for (var week = 1; week <= program.durationWeeks; week++) {
      for (final session in sortedSessions) {
        if (!_templateExists(session.kind, session.templateKey)) {
          continue;
        }
        final scheduledAt = _scheduledDate(
          program.startDate,
          week,
          session.weekDay,
          session.hour,
          session.minute,
        );

        final existing = _scheduleBox().values.where((s) {
          return s.programKey == programKey &&
              s.programWeek == week &&
              s.programSessionId == session.id;
        }).toList();
        if (existing.isNotEmpty) continue;

        final scheduleKey = await _scheduleBox().add(
          ScheduledWorkout(
            kind: session.kind,
            templateKey: session.templateKey,
            scheduledAt: scheduledAt,
            reminderEnabled: session.reminderEnabled,
            programKey: programKey,
            programWeek: week,
            programSessionId: session.id,
            isAutoGenerated: true,
          ),
        );

        if (session.reminderEnabled) {
          final title = 'Workout reminder';
          final body = '${_templateTitle(session.kind, session.templateKey)} - ${_fmtDateTime(scheduledAt)}';
          await WorkoutReminderService.instance.scheduleReminder(
            scheduleKey: scheduleKey,
            scheduledAt: scheduledAt,
            title: title,
            body: body,
          );
        }
      }
    }

    program.generatedUntilWeek = max(program.generatedUntilWeek, program.durationWeeks);
    await program.save();
  }

  static ({double weightKg, int reps, int? seconds}) tuneStrengthSet({
    ScheduledWorkout? schedule,
    required TemplateSet baseSet,
    int requiredSetCount = 1,
  }) {
    final program = schedule == null ? null : programForSchedule(schedule);
    final config = program?.progression;
    final settings = _readTuningSettings();
    final week = schedule?.programWeek ?? 1;
    final readiness = settings.autoProgressionEnabled
        ? _latestReadiness()
        : (loadModifier: 1.0, volumeModifier: 1.0);
    final categoryByExercise = _exerciseCategoryMap();
    final targetReps = baseSet.reps <= 0 ? 1 : baseSet.reps;
    final metTarget = _latestSessionMetTarget(
      exercise: baseSet.exercise,
      targetReps: targetReps,
      requiredSetCount: requiredSetCount,
    );
    final increment = _incrementForExercise(
      exercise: baseSet.exercise,
      settings: settings,
      categoryByExercise: categoryByExercise,
    );

    var weight = baseSet.weightKg;
    if (config != null) {
      final strengthSteps = _stepsForWeek(week, config.strengthStepEveryWeeks);
      if (config.strengthMode == 'fixed_kg') {
        weight += strengthSteps * config.strengthStepValueKg;
      } else if (config.strengthMode == 'percent') {
        weight *= (1 + ((config.strengthStepPercent * strengthSteps) / 100));
      }
    }

    var loadFactor = 1.0;
    if (config != null && _isDeloadWeek(config, week)) {
      loadFactor *= max(0.2, 1 + (config.deloadLoadPercent / 100));
    }

    // Positive jumps are allowed only when last comparable session hit target reps.
    if (settings.autoProgressionEnabled && metTarget) {
      weight += increment;
    } else if (weight > baseSet.weightKg) {
      weight = baseSet.weightKg;
    }

    // Readiness can reduce load, but does not add load above planned targets.
    if (settings.autoProgressionEnabled && readiness.loadModifier < 1.0) {
      loadFactor *= readiness.loadModifier;
    }
    weight *= loadFactor;
    if (!metTarget && weight > baseSet.weightKg) {
      weight = baseSet.weightKg;
    }

    final roundStep = settings.plateIncrement > 0 ? settings.plateIncrement : 2.5;
    final double clampedWeight = max<double>(0, weight);
    final hasWeightAdjustment = (clampedWeight - baseSet.weightKg).abs() > 0.0001;
    final double tunedWeight = hasWeightAdjustment
        ? _roundToStep(clampedWeight, roundStep)
        : max<double>(0, baseSet.weightKg);

    var volumeFactor = 1.0;
    if (settings.volumeMode == 'auto') {
      if (config != null && _isDeloadWeek(config, week)) {
        volumeFactor *= max(0.2, 1 + (config.deloadVolumePercent / 100));
      }
      if (settings.autoProgressionEnabled) {
        volumeFactor *= readiness.volumeModifier;
      }
    }

    if (baseSet.isTimeBased) {
      final baseSeconds = baseSet.seconds ?? 0;
      final tunedSeconds = volumeFactor == 1.0
          ? baseSet.seconds
          : max(1, (baseSeconds * volumeFactor).round());
      return (
        weightKg: tunedWeight,
        reps: baseSet.reps,
        seconds: tunedSeconds,
      );
    }

    final tunedReps = volumeFactor == 1.0
        ? baseSet.reps
        : max(1, (baseSet.reps * volumeFactor).round());
    return (
      weightKg: tunedWeight,
      reps: tunedReps,
      seconds: baseSet.seconds,
    );
  }

  static CardioTemplate tuneCardioTemplate({
    ScheduledWorkout? schedule,
    required CardioTemplate baseTemplate,
  }) {
    final program = schedule == null ? null : programForSchedule(schedule);
    final config = program?.progression;
    final settings = _readTuningSettings();
    if (config == null && settings.volumeMode != 'auto') {
      return CardioTemplate(
        name: baseTemplate.name,
        activity: baseTemplate.activity,
        durationSeconds: baseTemplate.durationSeconds,
        distanceKm: baseTemplate.distanceKm,
        elevationGainM: baseTemplate.elevationGainM,
        inclinePercent: baseTemplate.inclinePercent,
        avgHeartRate: baseTemplate.avgHeartRate,
        maxHeartRate: baseTemplate.maxHeartRate,
        rpe: baseTemplate.rpe,
        calories: baseTemplate.calories,
        zoneSeconds: List<int>.from(baseTemplate.zoneSeconds),
        segments: baseTemplate.segments.map((s) => s.copy()).toList(),
        environment: baseTemplate.environment,
        terrain: baseTemplate.terrain,
        weather: baseTemplate.weather,
        equipment: baseTemplate.equipment,
        mood: baseTemplate.mood,
        energy: baseTemplate.energy,
        notes: baseTemplate.notes,
      );
    }

    final readiness = settings.autoProgressionEnabled
        ? _latestReadiness()
        : (loadModifier: 1.0, volumeModifier: 1.0);
    final week = schedule?.programWeek ?? 1;
    final cardioSteps = config == null ? 0 : _stepsForWeek(week, config.cardioStepEveryWeeks);
    final segments = baseTemplate.segments.map((s) => s.copy()).toList();

    if (settings.volumeMode == 'auto' && config != null) {
      if (config.cardioMode == 'duration_seconds' && cardioSteps > 0) {
        final add = cardioSteps * config.cardioStepValueSeconds;
        _addSecondsToSegments(
          segments,
          add,
          preferWorkSegments: true,
          distributeAcrossTargets: true,
        );
      } else if (config.cardioMode == 'work_interval_seconds' && cardioSteps > 0) {
        final add = cardioSteps * config.cardioWorkIntervalStepSeconds;
        _addSecondsToSegments(segments, add, preferWorkSegments: true, onlyWork: true);
      }
    }

    var volumeFactor = 1.0;
    if (settings.volumeMode == 'auto') {
      if (config != null && config.cardioMode == 'duration_percent' && cardioSteps > 0) {
        volumeFactor *= (1 + ((config.cardioStepPercent * cardioSteps) / 100));
      }
      if (config != null && _isDeloadWeek(config, week)) {
        volumeFactor *= max(0.2, 1 + (config.deloadVolumePercent / 100));
      }
      if (settings.autoProgressionEnabled) {
        volumeFactor *= readiness.volumeModifier;
      }
    }

    for (final seg in segments) {
      seg.durationSeconds = max(1, (seg.durationSeconds * volumeFactor).round());
    }

    final duration = segments.fold<int>(0, (sum, seg) => sum + seg.durationSeconds);
    final distance = baseTemplate.distanceKm == null ? null : baseTemplate.distanceKm! * volumeFactor;

    return CardioTemplate(
      name: baseTemplate.name,
      activity: baseTemplate.activity,
      durationSeconds: duration,
      distanceKm: distance,
      elevationGainM: baseTemplate.elevationGainM,
      inclinePercent: baseTemplate.inclinePercent,
      avgHeartRate: baseTemplate.avgHeartRate,
      maxHeartRate: baseTemplate.maxHeartRate,
      rpe: baseTemplate.rpe,
      calories: baseTemplate.calories,
      zoneSeconds: List<int>.from(baseTemplate.zoneSeconds),
      segments: segments,
      environment: baseTemplate.environment,
      terrain: baseTemplate.terrain,
      weather: baseTemplate.weather,
      equipment: baseTemplate.equipment,
      mood: baseTemplate.mood,
      energy: baseTemplate.energy,
      notes: baseTemplate.notes,
    );
  }

  static DateTime _scheduledDate(
    DateTime programStart,
    int week,
    int weekDay,
    int hour,
    int minute,
  ) {
    final startWeek = _startOfWeek(programStart);
    final dayOffset = ((week - 1) * 7) + (weekDay - 1);
    final date = startWeek.add(Duration(days: dayOffset));
    return DateTime(date.year, date.month, date.day, hour, minute);
  }

  static DateTime _startOfWeek(DateTime d) {
    final date = DateTime(d.year, d.month, d.day);
    return date.subtract(Duration(days: date.weekday - 1));
  }

  static int _stepsForWeek(int week, int everyWeeks) {
    if (week <= 1 || everyWeeks <= 0) return 0;
    return (week - 1) ~/ everyWeeks;
  }

  static bool _isDeloadWeek(ProgramProgressionConfig config, int week) {
    if (!config.deloadEnabled) return false;
    if (config.deloadEveryWeeks <= 0) return false;
    return week > 0 && week % config.deloadEveryWeeks == 0;
  }

  static ({double loadModifier, double volumeModifier}) _latestReadiness() {
    try {
      final box = Hive.box<ReadinessEntry>('readiness');
      if (box.isEmpty) return (loadModifier: 1.0, volumeModifier: 1.0);
      final list = box.values.toList()..sort((a, b) => b.date.compareTo(a.date));
      final latest = list.first;
      return (
        loadModifier: latest.loadModifier,
        volumeModifier: latest.volumeModifier,
      );
    } catch (_) {
      return (loadModifier: 1.0, volumeModifier: 1.0);
    }
  }

  static double _roundToStep(double value, double step) {
    if (step <= 0) return value;
    return (value / step).round() * step;
  }

  static void _addSecondsToSegments(
    List<CardioSegment> segments,
    int seconds, {
    bool preferWorkSegments = false,
    bool onlyWork = false,
    bool distributeAcrossTargets = false,
  }) {
    if (seconds <= 0 || segments.isEmpty) return;

    List<CardioSegment> targets;
    if (onlyWork) {
      targets = segments.where((s) => s.type == 'work').toList();
      if (targets.isEmpty) return;
    } else if (preferWorkSegments) {
      targets = segments.where((s) => s.type == 'work').toList();
      if (targets.isEmpty) targets = segments;
    } else {
      targets = segments;
    }

    if (distributeAcrossTargets) {
      final each = seconds ~/ targets.length;
      final remainder = seconds % targets.length;
      for (var i = 0; i < targets.length; i++) {
        targets[i].durationSeconds += each + (i < remainder ? 1 : 0);
      }
      return;
    }

    for (final seg in targets) {
      seg.durationSeconds += seconds;
    }
  }

  static String _templateTitle(String kind, int templateKey) {
    if (kind == 'cardio') {
      return _cardioTemplates().get(templateKey)?.name ?? 'Cardio';
    }
    return _strengthTemplates().get(templateKey)?.name ?? 'Strength';
  }

  static bool _templateExists(String kind, int templateKey) {
    if (kind == 'cardio') return _cardioTemplates().get(templateKey) != null;
    return _strengthTemplates().get(templateKey) != null;
  }

  static String _fmtDateTime(DateTime d) {
    final mm = d.month.toString().padLeft(2, '0');
    final dd = d.day.toString().padLeft(2, '0');
    final hh = d.hour.toString().padLeft(2, '0');
    final min = d.minute.toString().padLeft(2, '0');
    return '$dd.$mm.${d.year} $hh:$min';
  }

  static _TuningSettings _readTuningSettings() {
    final settings = Hive.box('settings');
    final plateIncrement = (settings.get('plateIncrement') as num?)?.toDouble() ?? 2.5;
    final storedIncrease = (settings.get('weightIncreaseKg') as num?)?.toDouble();
    final useCustomIncrease = (settings.get('useCustomIncrease') as bool?) ?? false;
    final autoProgressionEnabled = (settings.get('autoProgressionEnabled') as bool?) ?? false;
    final volumeModeRaw = (settings.get('volumeMode') as String?) ?? 'auto';
    final volumeMode = volumeModeRaw == 'fixed' ? 'fixed' : 'auto';
    final categoryIncrements = _parseCategoryIncrements(settings.get('categoryIncrements'));

    final normalizedPlate = plateIncrement > 0 ? plateIncrement : 2.5;
    final normalizedIncrease = (storedIncrease != null && storedIncrease > 0)
        ? storedIncrease
        : normalizedPlate;

    return _TuningSettings(
      autoProgressionEnabled: autoProgressionEnabled,
      plateIncrement: normalizedPlate,
      weightIncreaseKg: normalizedIncrease,
      useCustomIncrease: useCustomIncrease,
      volumeMode: volumeMode,
      categoryIncrements: categoryIncrements,
    );
  }

  static Map<String, double> _parseCategoryIncrements(dynamic raw) {
    if (raw is! Map) return const {};
    final parsed = <String, double>{};
    raw.forEach((key, value) {
      if (key is! String || value is! num) return;
      final normalized = value.toDouble();
      if (normalized > 0) {
        parsed[key] = normalized;
      }
    });
    return parsed;
  }

  static Map<String, String> _exerciseCategoryMap() {
    final map = <String, String>{};
    try {
      final ebox = Hive.box<Exercise>('exercises');
      for (final e in ebox.values) {
        final name = e.name.trim().toLowerCase();
        final category = e.category.trim();
        if (name.isEmpty || category.isEmpty) continue;
        map[name] = category;
      }
    } catch (_) {
      // ignore
    }
    return map;
  }

  static double _incrementForExercise({
    required String exercise,
    required _TuningSettings settings,
    required Map<String, String> categoryByExercise,
  }) {
    final key = exercise.trim().toLowerCase();
    final category = categoryByExercise[key];
    if (category != null) {
      final override = settings.categoryIncrements[category];
      if (override != null && override > 0) return override;
    }
    if (settings.useCustomIncrease && settings.weightIncreaseKg > 0) {
      return settings.weightIncreaseKg;
    }
    return settings.plateIncrement > 0 ? settings.plateIncrement : 2.5;
  }

  static bool _latestSessionMetTarget({
    required String exercise,
    required int targetReps,
    required int requiredSetCount,
  }) {
    final normalizedExercise = exercise.trim().toLowerCase();
    final requiredCount = max(1, requiredSetCount);
    if (normalizedExercise.isEmpty || targetReps <= 0) return false;

    try {
      final workouts = Hive.box<Workout>('workouts').values.toList()
        ..sort((a, b) => b.date.compareTo(a.date));
      final sets = Hive.box<SetEntry>('sets').values;
      final byWorkout = <int, List<SetEntry>>{};

      for (final entry in sets) {
        if (entry.isTimeBased) continue;
        if (entry.exercise.trim().toLowerCase() != normalizedExercise) continue;
        byWorkout.putIfAbsent(entry.workoutKey, () => <SetEntry>[]).add(entry);
      }

      for (final workout in workouts) {
        final key = workout.key;
        if (key is! int) continue;
        final entries = byWorkout[key];
        if (entries == null || entries.isEmpty) continue;
        final completed = entries.where((e) => e.isCompleted).toList();
        final source = completed.length >= requiredCount ? completed : entries;
        if (source.length < requiredCount) continue;
        final ordered = source..sort((a, b) => a.setNumber.compareTo(b.setNumber));
        final comparable = ordered.take(requiredCount);
        return comparable.every((set) => set.reps >= targetReps);
      }
    } catch (_) {
      return false;
    }

    return false;
  }
}

class _TuningSettings {
  const _TuningSettings({
    required this.autoProgressionEnabled,
    required this.plateIncrement,
    required this.weightIncreaseKg,
    required this.useCustomIncrease,
    required this.volumeMode,
    required this.categoryIncrements,
  });

  final bool autoProgressionEnabled;
  final double plateIncrement;
  final double weightIncreaseKg;
  final bool useCustomIncrease;
  final String volumeMode;
  final Map<String, double> categoryIncrements;
}
