import 'dart:math';

import 'package:hive/hive.dart';

import '../models/cardio_entry.dart';
import '../models/cardio_template.dart';
import '../models/program_block.dart';
import '../models/readiness_entry.dart';
import '../models/scheduled_workout.dart';
import '../models/workout_template.dart';
import 'workout_reminder_service.dart';

class ProgramService {
  ProgramService._();

  static Box<ProgramBlock> _programBox() => Hive.box<ProgramBlock>('program_blocks');
  static Box<ScheduledWorkout> _scheduleBox() => Hive.box<ScheduledWorkout>('scheduled_workouts');
  static Box<WorkoutTemplate> _strengthTemplates() => Hive.box<WorkoutTemplate>('templates');
  static Box<CardioTemplate> _cardioTemplates() => Hive.box<CardioTemplate>('cardio_templates');

  static ProgramBlock? programForSchedule(ScheduledWorkout schedule) {
    final key = schedule.programKey;
    if (key == null) return null;
    return _programBox().get(key);
  }

  static Future<int> upsertProgram(ProgramBlock block, {int? key}) async {
    if (key == null) return _programBox().add(block);
    await _programBox().put(key, block);
    return key;
  }

  static Future<void> regenerateSchedulesForProgram({
    required int programKey,
    bool removeExistingAutoGenerated = true,
  }) async {
    final program = _programBox().get(programKey);
    if (program == null || !program.isActive || program.sessions.isEmpty) return;

    if (removeExistingAutoGenerated) {
      final toRemove = <int>[];
      for (final schedule in _scheduleBox().values) {
        if (schedule.programKey != programKey) continue;
        if (!schedule.isAutoGenerated) continue;
        if (schedule.isCompleted || schedule.linkedWorkoutKey != null) continue;
        toRemove.add(schedule.key as int);
      }
      for (final key in toRemove) {
        await WorkoutReminderService.instance.cancelReminder(key);
        await _scheduleBox().delete(key);
      }
    }

    final sortedSessions = [...program.sessions]
      ..sort((a, b) {
        final byDay = a.weekDay.compareTo(b.weekDay);
        if (byDay != 0) return byDay;
        final byHour = a.hour.compareTo(b.hour);
        if (byHour != 0) return byHour;
        return a.minute.compareTo(b.minute);
      });

    for (var week = 1; week <= program.durationWeeks; week++) {
      for (final session in sortedSessions) {
        if (!_templateExists(session.kind, session.templateKey)) {
          continue;
        }
        final scheduledAt = _scheduledDate(
          program.startDate,
          week,
          session.weekDay,
          session.hour,
          session.minute,
        );

        final existing = _scheduleBox().values.where((s) {
          return s.programKey == programKey &&
              s.programWeek == week &&
              s.programSessionId == session.id;
        }).toList();
        if (existing.isNotEmpty) continue;

        final scheduleKey = await _scheduleBox().add(
          ScheduledWorkout(
            kind: session.kind,
            templateKey: session.templateKey,
            scheduledAt: scheduledAt,
            reminderEnabled: session.reminderEnabled,
            programKey: programKey,
            programWeek: week,
            programSessionId: session.id,
            isAutoGenerated: true,
          ),
        );

        if (session.reminderEnabled) {
          final title = 'Workout reminder';
          final body = '${_templateTitle(session.kind, session.templateKey)} - ${_fmtDateTime(scheduledAt)}';
          await WorkoutReminderService.instance.scheduleReminder(
            scheduleKey: scheduleKey,
            scheduledAt: scheduledAt,
            title: title,
            body: body,
          );
        }
      }
    }

    program.generatedUntilWeek = max(program.generatedUntilWeek, program.durationWeeks);
    await program.save();
  }

  static ({double weightKg, int reps, int? seconds}) tuneStrengthSet({
    required ScheduledWorkout schedule,
    required TemplateSet baseSet,
  }) {
    final program = programForSchedule(schedule);
    final config = program?.progression;
    if (config == null) {
      return (
        weightKg: baseSet.weightKg,
        reps: baseSet.reps,
        seconds: baseSet.seconds,
      );
    }

    final week = schedule.programWeek ?? 1;
    final strengthSteps = _stepsForWeek(week, config.strengthStepEveryWeeks);

    var weight = baseSet.weightKg;
    if (config.strengthMode == 'fixed_kg') {
      weight += strengthSteps * config.strengthStepValueKg;
    } else if (config.strengthMode == 'percent') {
      weight *= (1 + ((config.strengthStepPercent * strengthSteps) / 100));
    }

    var loadFactor = 1.0;
    var volumeFactor = 1.0;

    if (_isDeloadWeek(config, week)) {
      loadFactor *= max(0.2, 1 + (config.deloadLoadPercent / 100));
      volumeFactor *= max(0.2, 1 + (config.deloadVolumePercent / 100));
    }

    if (config.applyReadinessModifiers) {
      final readiness = _latestReadiness();
      loadFactor *= readiness.loadModifier;
      volumeFactor *= readiness.volumeModifier;
    }

    final roundStep = config.strengthRoundingKg <= 0 ? 0.5 : config.strengthRoundingKg;
    final tunedWeight = _roundToStep(weight * loadFactor, roundStep);

    if (baseSet.isTimeBased) {
      final baseSeconds = baseSet.seconds ?? 0;
      return (
        weightKg: tunedWeight,
        reps: baseSet.reps,
        seconds: max(1, (baseSeconds * volumeFactor).round()),
      );
    }

    return (
      weightKg: tunedWeight,
      reps: max(1, (baseSet.reps * volumeFactor).round()),
      seconds: baseSet.seconds,
    );
  }

  static CardioTemplate tuneCardioTemplate({
    required ScheduledWorkout schedule,
    required CardioTemplate baseTemplate,
  }) {
    final program = programForSchedule(schedule);
    final config = program?.progression;
    if (config == null) {
      return CardioTemplate(
        name: baseTemplate.name,
        activity: baseTemplate.activity,
        durationSeconds: baseTemplate.durationSeconds,
        distanceKm: baseTemplate.distanceKm,
        elevationGainM: baseTemplate.elevationGainM,
        inclinePercent: baseTemplate.inclinePercent,
        avgHeartRate: baseTemplate.avgHeartRate,
        maxHeartRate: baseTemplate.maxHeartRate,
        rpe: baseTemplate.rpe,
        calories: baseTemplate.calories,
        zoneSeconds: List<int>.from(baseTemplate.zoneSeconds),
        segments: baseTemplate.segments.map((s) => s.copy()).toList(),
        environment: baseTemplate.environment,
        terrain: baseTemplate.terrain,
        weather: baseTemplate.weather,
        equipment: baseTemplate.equipment,
        mood: baseTemplate.mood,
        energy: baseTemplate.energy,
        notes: baseTemplate.notes,
      );
    }

    final week = schedule.programWeek ?? 1;
    final cardioSteps = _stepsForWeek(week, config.cardioStepEveryWeeks);
    final segments = baseTemplate.segments.map((s) => s.copy()).toList();

    if (config.cardioMode == 'duration_seconds' && cardioSteps > 0) {
      final add = cardioSteps * config.cardioStepValueSeconds;
      _addSecondsToSegments(
        segments,
        add,
        preferWorkSegments: true,
        distributeAcrossTargets: true,
      );
    } else if (config.cardioMode == 'work_interval_seconds' && cardioSteps > 0) {
      final add = cardioSteps * config.cardioWorkIntervalStepSeconds;
      _addSecondsToSegments(segments, add, preferWorkSegments: true, onlyWork: true);
    }

    var volumeFactor = 1.0;
    if (config.cardioMode == 'duration_percent' && cardioSteps > 0) {
      volumeFactor *= (1 + ((config.cardioStepPercent * cardioSteps) / 100));
    }
    if (_isDeloadWeek(config, week)) {
      volumeFactor *= max(0.2, 1 + (config.deloadVolumePercent / 100));
    }
    if (config.applyReadinessModifiers) {
      final readiness = _latestReadiness();
      volumeFactor *= readiness.volumeModifier;
    }

    for (final seg in segments) {
      seg.durationSeconds = max(1, (seg.durationSeconds * volumeFactor).round());
    }

    final duration = segments.fold<int>(0, (sum, seg) => sum + seg.durationSeconds);
    final distance = baseTemplate.distanceKm == null ? null : baseTemplate.distanceKm! * volumeFactor;

    return CardioTemplate(
      name: baseTemplate.name,
      activity: baseTemplate.activity,
      durationSeconds: duration,
      distanceKm: distance,
      elevationGainM: baseTemplate.elevationGainM,
      inclinePercent: baseTemplate.inclinePercent,
      avgHeartRate: baseTemplate.avgHeartRate,
      maxHeartRate: baseTemplate.maxHeartRate,
      rpe: baseTemplate.rpe,
      calories: baseTemplate.calories,
      zoneSeconds: List<int>.from(baseTemplate.zoneSeconds),
      segments: segments,
      environment: baseTemplate.environment,
      terrain: baseTemplate.terrain,
      weather: baseTemplate.weather,
      equipment: baseTemplate.equipment,
      mood: baseTemplate.mood,
      energy: baseTemplate.energy,
      notes: baseTemplate.notes,
    );
  }

  static DateTime _scheduledDate(
    DateTime programStart,
    int week,
    int weekDay,
    int hour,
    int minute,
  ) {
    final startWeek = _startOfWeek(programStart);
    final dayOffset = ((week - 1) * 7) + (weekDay - 1);
    final date = startWeek.add(Duration(days: dayOffset));
    return DateTime(date.year, date.month, date.day, hour, minute);
  }

  static DateTime _startOfWeek(DateTime d) {
    final date = DateTime(d.year, d.month, d.day);
    return date.subtract(Duration(days: date.weekday - 1));
  }

  static int _stepsForWeek(int week, int everyWeeks) {
    if (week <= 1 || everyWeeks <= 0) return 0;
    return (week - 1) ~/ everyWeeks;
  }

  static bool _isDeloadWeek(ProgramProgressionConfig config, int week) {
    if (!config.deloadEnabled) return false;
    if (config.deloadEveryWeeks <= 0) return false;
    return week > 0 && week % config.deloadEveryWeeks == 0;
  }

  static ({double loadModifier, double volumeModifier}) _latestReadiness() {
    try {
      final box = Hive.box<ReadinessEntry>('readiness');
      if (box.isEmpty) return (loadModifier: 1.0, volumeModifier: 1.0);
      final list = box.values.toList()..sort((a, b) => b.date.compareTo(a.date));
      final latest = list.first;
      return (
        loadModifier: latest.loadModifier,
        volumeModifier: latest.volumeModifier,
      );
    } catch (_) {
      return (loadModifier: 1.0, volumeModifier: 1.0);
    }
  }

  static double _roundToStep(double value, double step) {
    if (step <= 0) return value;
    return (value / step).round() * step;
  }

  static void _addSecondsToSegments(
    List<CardioSegment> segments,
    int seconds, {
    bool preferWorkSegments = false,
    bool onlyWork = false,
    bool distributeAcrossTargets = false,
  }) {
    if (seconds <= 0 || segments.isEmpty) return;

    List<CardioSegment> targets;
    if (onlyWork) {
      targets = segments.where((s) => s.type == 'work').toList();
      if (targets.isEmpty) return;
    } else if (preferWorkSegments) {
      targets = segments.where((s) => s.type == 'work').toList();
      if (targets.isEmpty) targets = segments;
    } else {
      targets = segments;
    }

    if (distributeAcrossTargets) {
      final each = seconds ~/ targets.length;
      final remainder = seconds % targets.length;
      for (var i = 0; i < targets.length; i++) {
        targets[i].durationSeconds += each + (i < remainder ? 1 : 0);
      }
      return;
    }

    for (final seg in targets) {
      seg.durationSeconds += seconds;
    }
  }

  static String _templateTitle(String kind, int templateKey) {
    if (kind == 'cardio') {
      return _cardioTemplates().get(templateKey)?.name ?? 'Cardio';
    }
    return _strengthTemplates().get(templateKey)?.name ?? 'Strength';
  }

  static bool _templateExists(String kind, int templateKey) {
    if (kind == 'cardio') return _cardioTemplates().get(templateKey) != null;
    return _strengthTemplates().get(templateKey) != null;
  }

  static String _fmtDateTime(DateTime d) {
    final mm = d.month.toString().padLeft(2, '0');
    final dd = d.day.toString().padLeft(2, '0');
    final hh = d.hour.toString().padLeft(2, '0');
    final min = d.minute.toString().padLeft(2, '0');
    return '$dd.$mm.${d.year} $hh:$min';
  }
}
