import 'package:hive/hive.dart';

class ScheduledWorkout extends HiveObject {
  String kind; // 'strength' or 'cardio'
  int templateKey;
  DateTime scheduledAt;
  bool reminderEnabled;
  bool isCompleted;
  int? linkedWorkoutKey;
  int? programKey;
  int? programWeek;
  String? programSessionId;
  bool isAutoGenerated;

  ScheduledWorkout({
    required this.kind,
    required this.templateKey,
    required this.scheduledAt,
    this.reminderEnabled = true,
    this.isCompleted = false,
    this.linkedWorkoutKey,
    this.programKey,
    this.programWeek,
    this.programSessionId,
    this.isAutoGenerated = false,
  });
}

class ScheduledWorkoutAdapter extends TypeAdapter<ScheduledWorkout> {
  @override
  final int typeId = 15;

  @override
  ScheduledWorkout read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{};
    for (var i = 0; i < numOfFields; i++) {
      fields[reader.readByte()] = reader.read();
    }
    return ScheduledWorkout(
      kind: (fields[0] as String?) ?? 'strength',
      templateKey: (fields[1] as int?) ?? -1,
      scheduledAt: (fields[2] as DateTime?) ?? DateTime.now(),
      reminderEnabled: (fields[3] as bool?) ?? true,
      isCompleted: (fields[4] as bool?) ?? false,
      linkedWorkoutKey: fields[5] as int?,
      programKey: fields[6] as int?,
      programWeek: fields[7] as int?,
      programSessionId: fields[8] as String?,
      isAutoGenerated: (fields[9] as bool?) ?? false,
    );
  }

  @override
  void write(BinaryWriter writer, ScheduledWorkout obj) {
    writer
      ..writeByte(10)
      ..writeByte(0)
      ..write(obj.kind)
      ..writeByte(1)
      ..write(obj.templateKey)
      ..writeByte(2)
      ..write(obj.scheduledAt)
      ..writeByte(3)
      ..write(obj.reminderEnabled)
      ..writeByte(4)
      ..write(obj.isCompleted)
      ..writeByte(5)
      ..write(obj.linkedWorkoutKey)
      ..writeByte(6)
      ..write(obj.programKey)
      ..writeByte(7)
      ..write(obj.programWeek)
      ..writeByte(8)
      ..write(obj.programSessionId)
      ..writeByte(9)
      ..write(obj.isAutoGenerated);
  }
}
